openapi: 3.0.4
info:
    title: Inventory Service API
    version: 1.0.0
    description: |
        Inventory service manages product stock and temporary reservations.

        ## Core invariants (guaranteed by the service)
        - No overselling: available + reserved = totalStock.
        - Reservations are atomic: either all items are reserved or none.
        - Reservations expire automatically after TTL.
        - Attaching a reservation to an owner is idempotent.

servers:
    - url: http://inventory-service:8003/v1
      description: Internal Inventory Service

components:
    schemas:
        StockItem:
            type: object
            properties:
                productId:
                    type: string
                    format: uuid
                available:
                    type: integer
                reserved:
                    type: integer
                updatedAt:
                    type: string
                    format: date-time

        ReservationItem:
            type: object
            required: [productId, quantity]
            properties:
                productId:
                    type: string
                    format: uuid
                quantity:
                    type: integer
                    minimum: 1

        Reservation:
            type: object
            properties:
                reservationId:
                    type: string
                    format: uuid
                items:
                    type: array
                    items:
                        $ref: "#/components/schemas/ReservationItem"
                status:
                    type: string
                    enum: [ACTIVE, CONFIRMED, RELEASED, EXPIRED]
                ownerType:
                    type: string
                ownerId:
                    type: string
                    nullable: true
                createdAt:
                    type: string
                    format: date-time
                expiresAt:
                    type: string
                    format: date-time

        Error:
            type: object
            properties:
                code:
                    type: string
                message:
                    type: string
                details:
                    type: array
                    items:
                        type: string

paths:
    ###############################################
    # 1. Create Reservation (atomic operation)
    ###############################################
    /reservations:
        post:
            summary: Create a stock reservation (atomic)
            description: |
                Attempts to reserve all requested items atomically.
                Either all items are reserved or none are.
            tags: [Reservations]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            required: [items]
                            properties:
                                items:
                                    type: array
                                    items:
                                        $ref: "#/components/schemas/ReservationItem"
                                ttlMinutes:
                                    type: integer
                                    default: 15
            responses:
                "201":
                    description: Reservation created
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Reservation"
                "409":
                    description: Insufficient stock
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                            examples:
                                out_of_stock:
                                    value:
                                        code: "OUT_OF_STOCK"
                                        message: "Not enough available stock"
                "400":
                    description: Invalid request

    ###############################################
    # 2. Get Reservation
    ###############################################
    /reservations/{reservationId}:
        get:
            tags: [Reservations]
            parameters:
                - name: reservationId
                  in: path
                  required: true
                  schema:
                      type: string
                      format: uuid
            responses:
                "200":
                    description: Reservation info
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Reservation"
                "404":
                    description: Reservation not found

        ###############################################
        # 3. Attach Reservation → Order / Cart (idempotent)
        ###############################################
        patch:
            tags: [Reservations]
            summary: Attach reservation to an owner (idempotent)
            description: |
                Attach a reservation to an owner (e.g., orderId).
                This operation is idempotent:
                 - re-attaching with same ownerId returns 200
                 - attaching with a *different* ownerId returns 409
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            required: [ownerType, ownerId]
                            properties:
                                ownerType:
                                    type: string
                                ownerId:
                                    type: string
                                    format: uuid
            responses:
                "200":
                    description: Attached successfully
                "409":
                    description: Reservation already attached to a different owner
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"

        ###############################################
        # 4. Release reservation (manual or compensation)
        ###############################################
        delete:
            tags: [Reservations]
            summary: Release reservation immediately
            description: |
                Releases reserved stock and marks the reservation as RELEASED.
                Used in compensation flows or cancellations.
            responses:
                "204":
                    description: Released

    ###############################################
    # 5. Stock lookup
    ###############################################
    /stock/{productId}:
        get:
            tags: [Stock]
            summary: Get stock info
            parameters:
                - name: productId
                  in: path
                  required: true
                  schema:
                      type: string
                      format: uuid
            responses:
                "200":
                    description: Stock info
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/StockItem"
                "404":
                    description: Product not found
