openapi: 3.0.4
info:
    title: Orders Service API
    version: 1.0.0
    description: API for managing customer orders
servers:
    - url: http://localhost:8000/v1
      description: Local Server
    - url: https://anirudhology.com/orders/v1
      description: Production Server

# Global components
components:
    schemas:
        Order:
            type: object
            required:
                - customerId
                - items
            properties:
                id:
                    type: string
                    format: uuid
                    readOnly: true
                customerId:
                    type: string
                    format: uuid
                status:
                    type: string
                    enum: [pending, processing, shipped, delivered, cancelled]
                    default: pending
                items:
                    type: array
                    items:
                        $ref: "#/components/schemas/OrderItem"
                totalAmount:
                    type: number
                    format: double
                    minimum: 0
                shippingAddress:
                    $ref: "#/components/schemas/Address"
                billingAddress:
                    $ref: "#/components/schemas/Address"
                createdAt:
                    type: string
                    format: date-time
                    readOnly: true
                updatedAt:
                    type: string
                    format: date-time
                    readOnly: true

        OrderItem:
            type: object
            required:
                - productId
                - quantity
            properties:
                productId:
                    type: string
                    format: uuid
                name:
                    type: string
                quantity:
                    type: integer
                    minimum: 1
                unitPrice:
                    type: number
                    format: double
                    minimum: 0
                subTotal:
                    type: number
                    format: double
                    readOnly: true

        Address:
            type: object
            properties:
                street:
                    type: string
                city:
                    type: string
                state:
                    type: string
                postalCode:
                    type: string
                country:
                    type: string
                    default: "IN"

        Error:
            type: object
            properties:
                code:
                    type: string
                message:
                    type: string
                details:
                    type: array
                    items:
                        type: string

    parameters:
        OrderId:
            name: orderId
            in: path
            required: true
            schema:
                type: string
                format: uuid

        PaginationLimit:
            name: limit
            in: query
            schema:
                type: integer
                default: 20
                maximum: 100

        PaginationOffset:
            name: offset
            in: query
            schema:
                type: integer
                default: 0
                minimum: 0

    responses:
        NotFound:
            description: Resource not found
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"

        BadRequest:
            description: Invalid request
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"

        Unauthorized:
            description: Authentication required
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
    
    securitySchemes:
        BearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
        ApiKeyAuth:
            type: apiKey
            in: header
            name: X-API-Key

# Paths (endpoints)
paths:
    /orders:
        get:
            summary: List all orders
            description: Retrieve a paginated list of orders with optional filters
            parameters:
                - $ref: "#/components/parameters/PaginationLimit"
                - $ref: "#/components/parameters/PaginationOffset"
                - name: status
                  in: query
                  schema:
                      type: string
                      enum: [pending, processing, shipped, delivered, cancelled]
                - name: customerId
                  in: query
                  schema:
                      type: string
                      format: uuid
            tags: [Orders]
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        type: array
                                        items:
                                            $ref: "#/components/schemas/Order"
                                    pagination:
                                        type: object
                                        properties:
                                            total:
                                                type: integer
                                            limit:
                                                type: integer
                                            offset:
                                                type: integer
                "401":
                    $ref: "#/components/responses/Unauthorized"
        
        post:
            summary: Create a new order
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - customerId
                                - items
                            properties:
                                customerId:
                                    type: string
                                    format: uuid
                                items:
                                    type: array
                                    items:
                                        $ref: "#/components/schemas/OrderItem"
                                    minItems: 1
                                shippingAddress:
                                    $ref: "#/components/schemas/Address"
                                billingAddress:
                                    $ref: "#/components/schemas/Address"
            tags: [Orders]
            responses:
                '201':
                    description: Order created successfully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Order"
                '400':
                    $ref: "#/components/responses/BadRequest"
    
    /orders/{orderId}:
        parameters:
            - $ref: "#/components/parameters/OrderId"
        
        get:
            summary: Get order by id
            responses:
                '200':
                    description: Order details
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Order"
                '404':
                    $ref: "#/components/responses/NotFound"
        
        put:
            summary: Update order
            description: Update order details (typically limited to certain fields)
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                status:
                                    type: string
                                    enum: [processing, shipped, delivered, cancelled]
                                shippingAddress:
                                    $ref: "#/components/schemas/Address"
            responses:
                '200':
                    description: Order updated
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Order"
                '400':
                    $ref: "#/components/responses/BadRequest"
                '404':
                    $ref: "#/components/responses/NotFound"
        
        delete:
            summary: Cancel order
            responses:
                '204':
                    description: Order cancelled successfully
                '404':
                    $ref: "#/components/responses/NotFound"
                '409':
                    description: Cannot cancel order in the current state

    /orders/{orderId}/items:
        parameters:
            - $ref: "#/components/parameters/OrderId"

        post:
            summary: Add item to order
            description: Add items to an existing order (if order is still editable)
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/OrderItem"
            tags: [Order Items]
            responses:
                '200':
                    description: Item added
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Order"



# Apply security globally
security:
    - BearerAuth: []

# Tags and Organization
tags:
    - name: Orders
      description: Order management operations
    - name: Order Items
      description: Order line item operations